# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\studioTools\maya\python\tool\publish\asset\assetPublishUI.ui'
#
# Created: Tue Nov 29 11:47:39 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui
from qtshim import Signal
from qtshim import wrapinstance


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AssetPublishWin(object):
    def setupUi(self, AssetPublishWin):
        AssetPublishWin.setObjectName(_fromUtf8("AssetPublishWin"))
        AssetPublishWin.resize(1109, 678)
        self.centralwidget = QtGui.QWidget(AssetPublishWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.assetName_label = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.assetName_label.setFont(font)
        self.assetName_label.setObjectName(_fromUtf8("assetName_label"))
        self.horizontalLayout.addWidget(self.assetName_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.publish_label = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.publish_label.setFont(font)
        self.publish_label.setObjectName(_fromUtf8("publish_label"))
        self.horizontalLayout_12.addWidget(self.publish_label)
        self.label_11 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.dependency_label = QtGui.QLabel(self.frame_7)
        self.dependency_label.setObjectName(_fromUtf8("dependency_label"))
        self.horizontalLayout_12.addWidget(self.dependency_label)
        self.label_17 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.output_label = QtGui.QLabel(self.frame_7)
        self.output_label.setObjectName(_fromUtf8("output_label"))
        self.horizontalLayout_12.addWidget(self.output_label)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 8)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 4)
        self.horizontalLayout_12.setStretch(4, 1)
        self.horizontalLayout_12.setStretch(5, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.line_2 = QtGui.QFrame(self.frame_7)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 6, 1, 1)
        self.subType_label = QtGui.QLabel(self.frame_7)
        self.subType_label.setObjectName(_fromUtf8("subType_label"))
        self.gridLayout.addWidget(self.subType_label, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.type_label = QtGui.QLabel(self.frame_7)
        self.type_label.setObjectName(_fromUtf8("type_label"))
        self.gridLayout.addWidget(self.type_label, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.project_label = QtGui.QLabel(self.frame_7)
        self.project_label.setObjectName(_fromUtf8("project_label"))
        self.gridLayout.addWidget(self.project_label, 0, 1, 1, 1)
        self.step_label = QtGui.QLabel(self.frame_7)
        self.step_label.setObjectName(_fromUtf8("step_label"))
        self.gridLayout.addWidget(self.step_label, 0, 7, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 3)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 3)
        self.gridLayout.setColumnStretch(6, 1)
        self.gridLayout.setColumnStretch(7, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.logo_label = QtGui.QLabel(self.frame_7)
        self.logo_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logo_label.setObjectName(_fromUtf8("logo_label"))
        self.horizontalLayout_4.addWidget(self.logo_label)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_9 = QtGui.QFrame(self.tab_5)
        self.frame_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_5 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_11.addWidget(self.label_5)
        self.snap_label = QtGui.QLabel(self.frame_9)
        self.snap_label.setObjectName(_fromUtf8("snap_label"))
        self.verticalLayout_11.addWidget(self.snap_label)
        self.line = QtGui.QFrame(self.frame_9)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_11.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.useMedia_checkBox = QtGui.QCheckBox(self.frame_9)
        self.useMedia_checkBox.setChecked(True)
        self.useMedia_checkBox.setObjectName(_fromUtf8("useMedia_checkBox"))
        self.gridLayout_3.addWidget(self.useMedia_checkBox, 1, 0, 1, 1)
        self.useThumb_checkBox = QtGui.QCheckBox(self.frame_9)
        self.useThumb_checkBox.setChecked(True)
        self.useThumb_checkBox.setObjectName(_fromUtf8("useThumb_checkBox"))
        self.gridLayout_3.addWidget(self.useThumb_checkBox, 0, 0, 1, 1)
        self.sendEmail_checkBox = QtGui.QCheckBox(self.frame_9)
        self.sendEmail_checkBox.setChecked(True)
        self.sendEmail_checkBox.setObjectName(_fromUtf8("sendEmail_checkBox"))
        self.gridLayout_3.addWidget(self.sendEmail_checkBox, 0, 1, 1, 1)
        self.debug_checkBox = QtGui.QCheckBox(self.frame_9)
        self.debug_checkBox.setObjectName(_fromUtf8("debug_checkBox"))
        self.gridLayout_3.addWidget(self.debug_checkBox, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.screenShot_pushButton = QtGui.QPushButton(self.frame_9)
        self.screenShot_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.screenShot_pushButton.setObjectName(_fromUtf8("screenShot_pushButton"))
        self.verticalLayout_11.addWidget(self.screenShot_pushButton)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 20)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.frame = QtGui.QFrame(self.tab_6)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.preview_label = QtGui.QLabel(self.frame)
        self.preview_label.setText(_fromUtf8(""))
        self.preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_label.setObjectName(_fromUtf8("preview_label"))
        self.verticalLayout_9.addWidget(self.preview_label)
        self.snap_pushButton = QtGui.QPushButton(self.frame)
        self.snap_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.snap_pushButton.setObjectName(_fromUtf8("snap_pushButton"))
        self.verticalLayout_9.addWidget(self.snap_pushButton)
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_9.addWidget(self.line_4)
        self.preview_label_2 = QtGui.QLabel(self.frame)
        self.preview_label_2.setObjectName(_fromUtf8("preview_label_2"))
        self.verticalLayout_9.addWidget(self.preview_label_2)
        self.message_plainTextEdit = QtGui.QPlainTextEdit(self.frame)
        self.message_plainTextEdit.setObjectName(_fromUtf8("message_plainTextEdit"))
        self.verticalLayout_9.addWidget(self.message_plainTextEdit)
        self.verticalLayout_9.setStretch(0, 4)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(4, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.line_5 = QtGui.QFrame(self.frame)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_9.addWidget(self.line_5)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.snap_listWidget = QtGui.QListWidget(self.frame)
        self.snap_listWidget.setFlow(QtGui.QListView.TopToBottom)
        self.snap_listWidget.setViewMode(QtGui.QListView.ListMode)
        self.snap_listWidget.setObjectName(_fromUtf8("snap_listWidget"))
        self.verticalLayout_14.addWidget(self.snap_listWidget)
        self.removeSnap_pushButton = QtGui.QPushButton(self.frame)
        self.removeSnap_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.removeSnap_pushButton.setObjectName(_fromUtf8("removeSnap_pushButton"))
        self.verticalLayout_14.addWidget(self.removeSnap_pushButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.horizontalLayout_9.setStretch(0, 4)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.setStretch(0, 4)
        self.verticalLayout_15.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.tabWidget)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.frame_10 = QtGui.QFrame(self.centralwidget)
        self.frame_10.setFrameShape(QtGui.QFrame.Box)
        self.frame_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_7 = QtGui.QLabel(self.frame_10)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_12.addWidget(self.label_7)
        self.publish_listWidget = QtGui.QListWidget(self.frame_10)
        self.publish_listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.publish_listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.publish_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.publish_listWidget.setObjectName(_fromUtf8("publish_listWidget"))
        self.verticalLayout_12.addWidget(self.publish_listWidget)
        self.label_16 = QtGui.QLabel(self.frame_10)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_12.addWidget(self.label_16)
        self.ref_listWidget = QtGui.QListWidget(self.frame_10)
        self.ref_listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ref_listWidget.setObjectName(_fromUtf8("ref_listWidget"))
        self.verticalLayout_12.addWidget(self.ref_listWidget)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 11)
        self.verticalLayout_12.setStretch(2, 1)
        self.verticalLayout_12.setStretch(3, 3)
        self.horizontalLayout_11.addWidget(self.frame_10)
        self.frame_8 = QtGui.QFrame(self.centralwidget)
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_2 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_10.addWidget(self.label_2)
        self.status_listWidget = QtGui.QListWidget(self.frame_8)
        self.status_listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.status_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.status_listWidget.setObjectName(_fromUtf8("status_listWidget"))
        self.verticalLayout_10.addWidget(self.status_listWidget)
        self.frame_11 = QtGui.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtGui.QFrame.Box)
        self.frame_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.frame_11)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.status_comboBox = QtGui.QComboBox(self.frame_11)
        self.status_comboBox.setObjectName(_fromUtf8("status_comboBox"))
        self.horizontalLayout_3.addWidget(self.status_comboBox)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_14 = QtGui.QLabel(self.frame_11)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.browse1_pushButton = QtGui.QPushButton(self.frame_11)
        self.browse1_pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browse1_pushButton.setObjectName(_fromUtf8("browse1_pushButton"))
        self.gridLayout_2.addWidget(self.browse1_pushButton, 1, 2, 1, 1)
        self.browse2_pushButton = QtGui.QPushButton(self.frame_11)
        self.browse2_pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browse2_pushButton.setObjectName(_fromUtf8("browse2_pushButton"))
        self.gridLayout_2.addWidget(self.browse2_pushButton, 2, 2, 1, 1)
        self.media_lineEdit = QtGui.QLineEdit(self.frame_11)
        self.media_lineEdit.setText(_fromUtf8(""))
        self.media_lineEdit.setObjectName(_fromUtf8("media_lineEdit"))
        self.gridLayout_2.addWidget(self.media_lineEdit, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_11)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.thumbnail_lineEdit = QtGui.QLineEdit(self.frame_11)
        self.thumbnail_lineEdit.setObjectName(_fromUtf8("thumbnail_lineEdit"))
        self.gridLayout_2.addWidget(self.thumbnail_lineEdit, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_2)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.incrementFile_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.incrementFile_lineEdit.setObjectName(_fromUtf8("incrementFile_lineEdit"))
        self.horizontalLayout_5.addWidget(self.incrementFile_lineEdit)
        self.incrementRoolFile_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.incrementRoolFile_checkBox.setObjectName(_fromUtf8("incrementRoolFile_checkBox"))
        self.horizontalLayout_5.addWidget(self.incrementRoolFile_checkBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.noBatch_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.noBatch_checkBox.setObjectName(_fromUtf8("noBatch_checkBox"))
        self.horizontalLayout_2.addWidget(self.noBatch_checkBox)
        self.texture_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.texture_checkBox.setChecked(True)
        self.texture_checkBox.setObjectName(_fromUtf8("texture_checkBox"))
        self.horizontalLayout_2.addWidget(self.texture_checkBox)
        self.publishFile_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.publishFile_checkBox.setChecked(True)
        self.publishFile_checkBox.setObjectName(_fromUtf8("publishFile_checkBox"))
        self.horizontalLayout_2.addWidget(self.publishFile_checkBox)
        self.publishShotgun_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.publishShotgun_checkBox.setChecked(True)
        self.publishShotgun_checkBox.setObjectName(_fromUtf8("publishShotgun_checkBox"))
        self.horizontalLayout_2.addWidget(self.publishShotgun_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.publish_pushButton = QtGui.QPushButton(self.centralwidget)
        self.publish_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.publish_pushButton.setObjectName(_fromUtf8("publish_pushButton"))
        self.verticalLayout_6.addWidget(self.publish_pushButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(0, 9)
        self.horizontalLayout_7.setStretch(1, 8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        AssetPublishWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AssetPublishWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        AssetPublishWin.setMenuBar(self.menubar)

        self.retranslateUi(AssetPublishWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AssetPublishWin)

    def retranslateUi(self, AssetPublishWin):
        AssetPublishWin.setWindowTitle(QtGui.QApplication.translate("AssetPublishWin", "PT Asset Publish v.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("AssetPublishWin", "AssetName : ", None, QtGui.QApplication.UnicodeUTF8))
        self.assetName_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("AssetPublishWin", "Publish File : ", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("AssetPublishWin", "Dependency : ", None, QtGui.QApplication.UnicodeUTF8))
        self.dependency_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("AssetPublishWin", "Output : ", None, QtGui.QApplication.UnicodeUTF8))
        self.output_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AssetPublishWin", "SubType : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("AssetPublishWin", "Step : ", None, QtGui.QApplication.UnicodeUTF8))
        self.subType_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AssetPublishWin", "Type : ", None, QtGui.QApplication.UnicodeUTF8))
        self.type_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AssetPublishWin", "Project : ", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.step_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_label.setText(QtGui.QApplication.translate("AssetPublishWin", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AssetPublishWin", "Snap", None, QtGui.QApplication.UnicodeUTF8))
        self.snap_label.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.useMedia_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "User as Media", None, QtGui.QApplication.UnicodeUTF8))
        self.useThumb_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Use as Thumbnails", None, QtGui.QApplication.UnicodeUTF8))
        self.sendEmail_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Send Email", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.screenShot_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "Screen Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("AssetPublishWin", "Snap", None, QtGui.QApplication.UnicodeUTF8))
        self.snap_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "Snap", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_label_2.setText(QtGui.QApplication.translate("AssetPublishWin", "Version Details : ", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSnap_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("AssetPublishWin", "Revision Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AssetPublishWin", "Published Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("AssetPublishWin", "Refs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AssetPublishWin", "Status : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("AssetPublishWin", "Status : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("AssetPublishWin", "Thumbnails : ", None, QtGui.QApplication.UnicodeUTF8))
        self.browse1_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.browse2_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("AssetPublishWin", "Media : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("AssetPublishWin", "File to increment : ", None, QtGui.QApplication.UnicodeUTF8))
        self.incrementRoolFile_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Use Root File", None, QtGui.QApplication.UnicodeUTF8))
        self.noBatch_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Run Batch mode in current session", None, QtGui.QApplication.UnicodeUTF8))
        self.texture_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Convert Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.publishFile_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Publish File", None, QtGui.QApplication.UnicodeUTF8))
        self.publishShotgun_checkBox.setText(QtGui.QApplication.translate("AssetPublishWin", "Publish Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_pushButton.setText(QtGui.QApplication.translate("AssetPublishWin", "Publish", None, QtGui.QApplication.UnicodeUTF8))

